<?php


function evol_vars_ztools_theme_setting() {
  // Your code comes here
  $definition = array(
    'name'    => t('Theme variables'),
    'form' => 'evol_vars_ztools_theme_setting_form',
    'form arguments' => array(),
    // 'path'    => NULL,
    // 'file'    => NULL,
    // 'module'  => NULL,
    // 'key'     => 'value',
  );
  return $definition;
}


function evol_vars_ztools_theme_setting_form() {
  
}